on:
  push:
    branches: ['latest']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - id: make_version_string
      uses: sandersaares-actions/make-version-string@master
      with:
        assemblyInfoPath: AssemblyInfo.cs
        primaryBranch: 'latest'
    - uses: sandersaares-actions/expand-tokens@master
      env:
        VERSIONSTRING: ${{ steps.make_version_string.outputs.versionstring }}
      with:
        path: Constants.cs
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: prometheusnet/docker_exporter:latest
        username: prometheusnet
        password: ${{ secrets.docker_hub_token }}
        snapshot: true
        buildoptions: '--label version=${{ steps.make_version_string.outputs.versionstring }}'